// Country display names derived from Unicode CLDR (English and Russian).
// Copyright © 2015-2024 Unicode, Inc. SPDX-License-Identifier: Unicode-3.0
// See docs/UNICODE_LICENSE.txt. Source revision: 1aaabe99aa652d6f22ea488cf25baea46aa69b42
// https://github.com/unicode-org/cldr-json/tree/1aaabe99aa652d6f22ea488cf25baea46aa69b42
// Macroregions, alternate political labels and unknown country codes are omitted.
package providerfeed

var countryLocaleNames = map[string]string{
	"Afghanistan":                            "AF",
	"Albania":                                "AL",
	"Algeria":                                "DZ",
	"American Samoa":                         "AS",
	"Andorra":                                "AD",
	"Angola":                                 "AO",
	"Anguilla":                               "AI",
	"Antarctica":                             "AQ",
	"Antigua & Barbuda":                      "AG",
	"Argentina":                              "AR",
	"Armenia":                                "AM",
	"Aruba":                                  "AW",
	"Australia":                              "AU",
	"Austria":                                "AT",
	"Azerbaijan":                             "AZ",
	"Bahamas":                                "BS",
	"Bahrain":                                "BH",
	"Bangladesh":                             "BD",
	"Barbados":                               "BB",
	"Belarus":                                "BY",
	"Belgium":                                "BE",
	"Belize":                                 "BZ",
	"Benin":                                  "BJ",
	"Bermuda":                                "BM",
	"Bhutan":                                 "BT",
	"Bolivia":                                "BO",
	"Bosnia & Herzegovina":                   "BA",
	"Botswana":                               "BW",
	"Bouvet Island":                          "BV",
	"Brazil":                                 "BR",
	"British Indian Ocean Territory":         "IO",
	"British Virgin Islands":                 "VG",
	"Brunei":                                 "BN",
	"Bulgaria":                               "BG",
	"Burkina Faso":                           "BF",
	"Burundi":                                "BI",
	"Cambodia":                               "KH",
	"Cameroon":                               "CM",
	"Canada":                                 "CA",
	"Cape Verde":                             "CV",
	"Caribbean Netherlands":                  "BQ",
	"Cayman Islands":                         "KY",
	"Central African Republic":               "CF",
	"Chad":                                   "TD",
	"Chile":                                  "CL",
	"China":                                  "CN",
	"Christmas Island":                       "CX",
	"Cocos (Keeling) Islands":                "CC",
	"Colombia":                               "CO",
	"Comoros":                                "KM",
	"Congo - Brazzaville":                    "CG",
	"Congo - Kinshasa":                       "CD",
	"Cook Islands":                           "CK",
	"Costa Rica":                             "CR",
	"Croatia":                                "HR",
	"Cuba":                                   "CU",
	"Curaçao":                                "CW",
	"Cyprus":                                 "CY",
	"Czechia":                                "CZ",
	"Côte d’Ivoire":                          "CI",
	"Denmark":                                "DK",
	"Djibouti":                               "DJ",
	"Dominica":                               "DM",
	"Dominican Republic":                     "DO",
	"Ecuador":                                "EC",
	"Egypt":                                  "EG",
	"El Salvador":                            "SV",
	"Equatorial Guinea":                      "GQ",
	"Eritrea":                                "ER",
	"Estonia":                                "EE",
	"Eswatini":                               "SZ",
	"Ethiopia":                               "ET",
	"Falkland Islands":                       "FK",
	"Faroe Islands":                          "FO",
	"Fiji":                                   "FJ",
	"Finland":                                "FI",
	"France":                                 "FR",
	"French Guiana":                          "GF",
	"French Polynesia":                       "PF",
	"French Southern Territories":            "TF",
	"Gabon":                                  "GA",
	"Gambia":                                 "GM",
	"Georgia":                                "GE",
	"Germany":                                "DE",
	"Ghana":                                  "GH",
	"Gibraltar":                              "GI",
	"Greece":                                 "GR",
	"Greenland":                              "GL",
	"Grenada":                                "GD",
	"Guadeloupe":                             "GP",
	"Guam":                                   "GU",
	"Guatemala":                              "GT",
	"Guernsey":                               "GG",
	"Guinea":                                 "GN",
	"Guinea-Bissau":                          "GW",
	"Guyana":                                 "GY",
	"Haiti":                                  "HT",
	"Heard & McDonald Islands":               "HM",
	"Honduras":                               "HN",
	"Hong Kong SAR China":                    "HK",
	"Hungary":                                "HU",
	"Iceland":                                "IS",
	"India":                                  "IN",
	"Indonesia":                              "ID",
	"Iran":                                   "IR",
	"Iraq":                                   "IQ",
	"Ireland":                                "IE",
	"Isle of Man":                            "IM",
	"Israel":                                 "IL",
	"Italy":                                  "IT",
	"Jamaica":                                "JM",
	"Japan":                                  "JP",
	"Jersey":                                 "JE",
	"Jordan":                                 "JO",
	"Kazakhstan":                             "KZ",
	"Kenya":                                  "KE",
	"Kiribati":                               "KI",
	"Kuwait":                                 "KW",
	"Kyrgyzstan":                             "KG",
	"Laos":                                   "LA",
	"Latvia":                                 "LV",
	"Lebanon":                                "LB",
	"Lesotho":                                "LS",
	"Liberia":                                "LR",
	"Libya":                                  "LY",
	"Liechtenstein":                          "LI",
	"Lithuania":                              "LT",
	"Luxembourg":                             "LU",
	"Macao SAR China":                        "MO",
	"Madagascar":                             "MG",
	"Malawi":                                 "MW",
	"Malaysia":                               "MY",
	"Maldives":                               "MV",
	"Mali":                                   "ML",
	"Malta":                                  "MT",
	"Marshall Islands":                       "MH",
	"Martinique":                             "MQ",
	"Mauritania":                             "MR",
	"Mauritius":                              "MU",
	"Mayotte":                                "YT",
	"Mexico":                                 "MX",
	"Micronesia":                             "FM",
	"Moldova":                                "MD",
	"Monaco":                                 "MC",
	"Mongolia":                               "MN",
	"Montenegro":                             "ME",
	"Montserrat":                             "MS",
	"Morocco":                                "MA",
	"Mozambique":                             "MZ",
	"Myanmar (Burma)":                        "MM",
	"Namibia":                                "NA",
	"Nauru":                                  "NR",
	"Nepal":                                  "NP",
	"Netherlands":                            "NL",
	"New Caledonia":                          "NC",
	"New Zealand":                            "NZ",
	"Nicaragua":                              "NI",
	"Niger":                                  "NE",
	"Nigeria":                                "NG",
	"Niue":                                   "NU",
	"Norfolk Island":                         "NF",
	"North Korea":                            "KP",
	"North Macedonia":                        "MK",
	"Northern Mariana Islands":               "MP",
	"Norway":                                 "NO",
	"Oman":                                   "OM",
	"Pakistan":                               "PK",
	"Palau":                                  "PW",
	"Palestinian Territories":                "PS",
	"Panama":                                 "PA",
	"Papua New Guinea":                       "PG",
	"Paraguay":                               "PY",
	"Peru":                                   "PE",
	"Philippines":                            "PH",
	"Pitcairn Islands":                       "PN",
	"Poland":                                 "PL",
	"Portugal":                               "PT",
	"Puerto Rico":                            "PR",
	"Qatar":                                  "QA",
	"Romania":                                "RO",
	"Russia":                                 "RU",
	"Rwanda":                                 "RW",
	"Réunion":                                "RE",
	"Samoa":                                  "WS",
	"San Marino":                             "SM",
	"Saudi Arabia":                           "SA",
	"Senegal":                                "SN",
	"Serbia":                                 "RS",
	"Seychelles":                             "SC",
	"Sierra Leone":                           "SL",
	"Singapore":                              "SG",
	"Sint Maarten":                           "SX",
	"Slovakia":                               "SK",
	"Slovenia":                               "SI",
	"Solomon Islands":                        "SB",
	"Somalia":                                "SO",
	"South Africa":                           "ZA",
	"South Georgia & South Sandwich Islands": "GS",
	"South Korea":                            "KR",
	"South Sudan":                            "SS",
	"Spain":                                  "ES",
	"Sri Lanka":                              "LK",
	"St. Barthélemy":                         "BL",
	"St. Helena":                             "SH",
	"St. Kitts & Nevis":                      "KN",
	"St. Lucia":                              "LC",
	"St. Martin":                             "MF",
	"St. Pierre & Miquelon":                  "PM",
	"St. Vincent & Grenadines":               "VC",
	"Sudan":                                  "SD",
	"Suriname":                               "SR",
	"Svalbard & Jan Mayen":                   "SJ",
	"Sweden":                                 "SE",
	"Switzerland":                            "CH",
	"Syria":                                  "SY",
	"São Tomé & Príncipe":                    "ST",
	"Taiwan":                                 "TW",
	"Tajikistan":                             "TJ",
	"Tanzania":                               "TZ",
	"Thailand":                               "TH",
	"Timor-Leste":                            "TL",
	"Togo":                                   "TG",
	"Tokelau":                                "TK",
	"Tonga":                                  "TO",
	"Trinidad & Tobago":                      "TT",
	"Tunisia":                                "TN",
	"Turkmenistan":                           "TM",
	"Turks & Caicos Islands":                 "TC",
	"Tuvalu":                                 "TV",
	"Türkiye":                                "TR",
	"U.S. Outlying Islands":                  "UM",
	"U.S. Virgin Islands":                    "VI",
	"Uganda":                                 "UG",
	"Ukraine":                                "UA",
	"United Arab Emirates":                   "AE",
	"United Kingdom":                         "GB",
	"United States":                          "US",
	"Uruguay":                                "UY",
	"Uzbekistan":                             "UZ",
	"Vanuatu":                                "VU",
	"Vatican City":                           "VA",
	"Venezuela":                              "VE",
	"Vietnam":                                "VN",
	"Wallis & Futuna":                        "WF",
	"Western Sahara":                         "EH",
	"Yemen":                                  "YE",
	"Zambia":                                 "ZM",
	"Zimbabwe":                               "ZW",
	"Åland Islands":                          "AX",
	"Австралия":                              "AU",
	"Австрия":                                "AT",
	"Азербайджан":                            "AZ",
	"Аландские о-ва":                         "AX",
	"Албания":                                "AL",
	"Алжир":                                  "DZ",
	"Американское Самоа":                     "AS",
	"Ангилья":                                "AI",
	"Ангола":                                 "AO",
	"Андорра":                                "AD",
	"Антарктида":                             "AQ",
	"Антигуа и Барбуда":                      "AG",
	"Аргентина":                              "AR",
	"Армения":                                "AM",
	"Аруба":                                  "AW",
	"Афганистан":                             "AF",
	"Багамы":                                 "BS",
	"Бангладеш":                              "BD",
	"Барбадос":                               "BB",
	"Бахрейн":                                "BH",
	"Беларусь":                               "BY",
	"Белиз":                                  "BZ",
	"Бельгия":                                "BE",
	"Бенин":                                  "BJ",
	"Бермудские о-ва":                        "BM",
	"Болгария":                               "BG",
	"Боливия":                                "BO",
	"Бонэйр, Синт-Эстатиус и Саба": "BQ",
	"Босния и Герцеговина":         "BA",
	"Ботсвана":                     "BW",
	"Бразилия":                     "BR",
	"Британская территория в Индийском океане": "IO",
	"Бруней":         "BN",
	"Буркина-Фасо":   "BF",
	"Бурунди":        "BI",
	"Бутан":          "BT",
	"Вануату":        "VU",
	"Ватикан":        "VA",
	"Великобритания": "GB",
	"Венгрия":        "HU",
	"Венесуэла":      "VE",
	"Виргинские о-ва (Великобритания)": "VG",
	"Виргинские о-ва (США)":            "VI",
	"Внешние малые о-ва (США)":         "UM",
	"Восточный Тимор":                  "TL",
	"Вьетнам":                          "VN",
	"Габон":                            "GA",
	"Гаити":                            "HT",
	"Гайана":                           "GY",
	"Гамбия":                           "GM",
	"Гана":                             "GH",
	"Гваделупа":                        "GP",
	"Гватемала":                        "GT",
	"Гвинея":                           "GN",
	"Гвинея-Бисау":                     "GW",
	"Германия":                         "DE",
	"Гернси":                           "GG",
	"Гибралтар":                        "GI",
	"Гондурас":                         "HN",
	"Гонконг (САР)":                    "HK",
	"Гренада":                          "GD",
	"Гренландия":                       "GL",
	"Греция":                           "GR",
	"Грузия":                           "GE",
	"Гуам":                             "GU",
	"Дания":                            "DK",
	"Джерси":                           "JE",
	"Джибути":                          "DJ",
	"Доминика":                         "DM",
	"Доминиканская Республика": "DO",
	"Египет":             "EG",
	"Замбия":             "ZM",
	"Западная Сахара":    "EH",
	"Зимбабве":           "ZW",
	"Израиль":            "IL",
	"Индия":              "IN",
	"Индонезия":          "ID",
	"Иордания":           "JO",
	"Ирак":               "IQ",
	"Иран":               "IR",
	"Ирландия":           "IE",
	"Исландия":           "IS",
	"Испания":            "ES",
	"Италия":             "IT",
	"Йемен":              "YE",
	"КНДР":               "KP",
	"Кабо-Верде":         "CV",
	"Казахстан":          "KZ",
	"Камбоджа":           "KH",
	"Камерун":            "CM",
	"Канада":             "CA",
	"Катар":              "QA",
	"Кения":              "KE",
	"Кипр":               "CY",
	"Киргизия":           "KG",
	"Кирибати":           "KI",
	"Китай":              "CN",
	"Кокосовые о-ва":     "CC",
	"Колумбия":           "CO",
	"Коморы":             "KM",
	"Конго - Браззавиль": "CG",
	"Конго - Киншаса":    "CD",
	"Коста-Рика":         "CR",
	"Кот-д’Ивуар":        "CI",
	"Куба":               "CU",
	"Кувейт":             "KW",
	"Кюрасао":            "CW",
	"Лаос":               "LA",
	"Латвия":             "LV",
	"Лесото":             "LS",
	"Либерия":            "LR",
	"Ливан":              "LB",
	"Ливия":              "LY",
	"Литва":              "LT",
	"Лихтенштейн":        "LI",
	"Люксембург":         "LU",
	"Маврикий":           "MU",
	"Мавритания":         "MR",
	"Мадагаскар":         "MG",
	"Майотта":            "YT",
	"Макао (САР)":        "MO",
	"Малави":             "MW",
	"Малайзия":           "MY",
	"Мали":               "ML",
	"Мальдивы":           "MV",
	"Мальта":             "MT",
	"Марокко":            "MA",
	"Мартиника":          "MQ",
	"Маршалловы о-ва":    "MH",
	"Мексика":            "MX",
	"Мозамбик":           "MZ",
	"Молдова":            "MD",
	"Монако":             "MC",
	"Монголия":           "MN",
	"Монтсеррат":         "MS",
	"Мьянма (Бирма)":     "MM",
	"Намибия":            "NA",
	"Науру":              "NR",
	"Непал":              "NP",
	"Нигер":              "NE",
	"Нигерия":            "NG",
	"Нидерланды":         "NL",
	"Никарагуа":          "NI",
	"Ниуэ":               "NU",
	"Новая Зеландия":     "NZ",
	"Новая Каледония":    "NC",
	"Норвегия":           "NO",
	"ОАЭ":                "AE",
	"Оман":               "OM",
	"Пакистан":           "PK",
	"Палау":              "PW",
	"Палестинские территории": "PS",
	"Панама":                   "PA",
	"Папуа — Новая Гвинея":     "PG",
	"Парагвай":                 "PY",
	"Перу":                     "PE",
	"Польша":                   "PL",
	"Португалия":               "PT",
	"Пуэрто-Рико":              "PR",
	"Республика Корея":         "KR",
	"Реюньон":                  "RE",
	"Россия":                   "RU",
	"Руанда":                   "RW",
	"Румыния":                  "RO",
	"Сальвадор":                "SV",
	"Самоа":                    "WS",
	"Сан-Марино":               "SM",
	"Сан-Томе и Принсипи":      "ST",
	"Саудовская Аравия":        "SA",
	"Северная Македония":       "MK",
	"Северные Марианские о-ва": "MP",
	"Сейшельские о-ва":         "SC",
	"Сен-Бартелеми":            "BL",
	"Сен-Мартен":               "MF",
	"Сен-Пьер и Микелон":       "PM",
	"Сенегал":                  "SN",
	"Сент-Винсент и Гренадины": "VC",
	"Сент-Китс и Невис":        "KN",
	"Сент-Люсия":               "LC",
	"Сербия":                   "RS",
	"Сингапур":                 "SG",
	"Синт-Мартен":              "SX",
	"Сирия":                    "SY",
	"Словакия":                 "SK",
	"Словения":                 "SI",
	"Соединенные Штаты":        "US",
	"Соломоновы о-ва":          "SB",
	"Сомали":                   "SO",
	"Судан":                    "SD",
	"Суринам":                  "SR",
	"Сьерра-Леоне":             "SL",
	"Таджикистан":              "TJ",
	"Таиланд":                  "TH",
	"Тайвань":                  "TW",
	"Танзания":                 "TZ",
	"Того":                     "TG",
	"Токелау":                  "TK",
	"Тонга":                    "TO",
	"Тринидад и Тобаго":        "TT",
	"Тувалу":                   "TV",
	"Тунис":                    "TN",
	"Туркменистан":             "TM",
	"Турция":                   "TR",
	"Тёркс и Кайкос":           "TC",
	"Уганда":                   "UG",
	"Узбекистан":               "UZ",
	"Украина":                  "UA",
	"Уоллис и Футуна":          "WF",
	"Уругвай":                  "UY",
	"Фарерские о-ва":           "FO",
	"Федеративные Штаты Микронезии": "FM",
	"Фиджи":                        "FJ",
	"Филиппины":                    "PH",
	"Финляндия":                    "FI",
	"Фолклендские о-ва":            "FK",
	"Франция":                      "FR",
	"Французская Гвиана":           "GF",
	"Французская Полинезия":        "PF",
	"Французские Южные территории": "TF",
	"Хорватия":                     "HR",
	"Центрально-Африканская Республика": "CF",
	"Чад":        "TD",
	"Черногория": "ME",
	"Чехия":      "CZ",
	"Чили":       "CL",
	"Швейцария":  "CH",
	"Швеция":     "SE",
	"Шпицберген и Ян-Майен": "SJ",
	"Шри-Ланка":             "LK",
	"Эквадор":               "EC",
	"Экваториальная Гвинея": "GQ",
	"Эритрея":               "ER",
	"Эсватини":              "SZ",
	"Эстония":               "EE",
	"Эфиопия":               "ET",
	"Южная Георгия и Южные Сандвичевы о-ва": "GS",
	"Южно-Африканская Республика":           "ZA",
	"Южный Судан":            "SS",
	"Ямайка":                 "JM",
	"Япония":                 "JP",
	"о-в Буве":               "BV",
	"о-в Мэн":                "IM",
	"о-в Норфолк":            "NF",
	"о-в Рождества":          "CX",
	"о-в Св. Елены":          "SH",
	"о-ва Кайман":            "KY",
	"о-ва Кука":              "CK",
	"о-ва Питкэрн":           "PN",
	"о-ва Херд и Макдональд": "HM",
}
